"set nu
syntax on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

" dark background support
set background=dark

" disable autoindent
"set ai 

set history=1000
set wildmenu


set title
"set number
set hlsearch
set showmode

set nobackup
set visualbell

