"set nu
syntax on
set tabstop=4       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.

set shiftwidth=4    " Indents will have a width of 4

set softtabstop=4   " Sets the number of columns for a TAB

"set expandtab       " Expand TABs to spaces

" dark background support
set background=dark

" disable autoindent
"set ai 

set history=1000
set wildmenu


set title
"set number
set hlsearch
set showmode

set nobackup
set visualbell

